name: Run Y Gyi Bot
on:
  repository_dispatch:
    types: [trigger-bot]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Bot Script
        run: node main.js
        env:
          # Pipedream မှ ပို့လိုက်သော payload တစ်ခုလုံးကို environment ထဲ ထည့်သည်
          INPUT_DATA: ${{ toJson(github.event.client_payload) }}
          
